apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quick-infra-net
  labels:
    app: quick-infra-net
spec:
  endpoints:
  - interval: 30s
    port: quick-infra-net
  selector:
    matchLabels:
      app: quick-infra-net