---
apiVersion: v1
kind: Service
metadata:
  name: quick-infra-net
  labels:
    app: quick-infra-net
spec:
  type: NodePort
  ports:
  - name: quick-infra-net
    port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: quick-infra-net